# Generated by Django 4.2.15 on 2024-09-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingo',
            old_name='enter_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='bingo',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='bingo',
            old_name='team_count',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='bingo',
            old_name='winner_bingo_count',
            new_name='teams',
        ),
    ]
