# Generated by Django 4.2.15 on 2024-09-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_rename_enter_code_bingo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bingo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_set', to='bingo.bingo'),
        ),
    ]
