# Generated by Django 4.2.15 on 2024-09-15 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_team_bingo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_team',
            name='unique_user_team',
        ),
        migrations.AlterField(
            model_name='bingo',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='teams',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bingocell',
            name='col',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bingocell',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
    ]
