# Generated by Django 4.2.15 on 2024-09-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bingo', '0004_remove_user_team_unique_user_team_alter_bingo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_bingo_count', models.PositiveIntegerField(default=0)),
                ('completed_cell_count', models.PositiveIntegerField(default=0)),
                ('bingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.team')),
            ],
        ),
    ]
